
<!Doctype html>
<html>
<head>
    <title>Add info</title>
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
    <link href="../src/styles/AddUserForm.css" type="text/css" rel="stylesheet">


</head>

<body>
<form action="../Controller/add_controller.php" method="post">
    <div class="form-style-8">
        <h2>Add Client</h2>
        <form>
            <input type="text" name="name" placeholder="Name">
            <input type="text" name="Address" placeholder="Address">
            <input type="date" name="birthday" placeholder="Birthday">
            <input type="text" name="gender" placeholder="Gender">
            <input type ="number" name="credit" placeholder="Credit">
            <input type="tel" name="phone" placeholder="Phone Number">
            <input type="submit" value="Add" name="addUserBtn"/>

        </form>
    </div>
</form>






</body>
</html>
