
<!Doctype html>
<html>
<head>
    <title>Add info</title>
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
    <link href="../src/styles/AddUserForm.css" type="text/css" rel="stylesheet">
    <link href="../src/styles/creditCard.css" type="text/css" rel="stylesheet">


</head>

<body>

<form action="../Controller/add_controller.php" method="post">
    <div class="form-style-8">
        <h2>Add Client</h2>
        <form>
            <input type="text" name="name" placeholder="Name">
            <input type="date" name="birthday" placeholder="Birthday">
            <input type="text" name="gender" placeholder="Gender">
            <input type="tel" name="phone" placeholder="Phone Number">
            <h4>Address:</h4>
            <input type="text" name="city" placeholder="City">
            <input type="text" name="street" placeholder="Street">
            <input type="text" name="home" placeholder="Home">
            <input type="number" name="index" placeholder="Index">
            <div style="text-align: center">
            <input style="display: inline-block; margin-top: 3vh; margin-right: 3vw;" type="submit" value="Add Client" name="addUserBtn"/>
            <input style="display: inline-block; margin-top: 3vh; margin-left: 3vw;" type="button" value="Add credit card" name="addCard" onclick="adddd()">
            </div>
        </form>
    </div>
</form>





<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

<form action="../Controller/add_controller.php" method="post">
<div  class="credit-card-wrapper">
    <div style="margin-left: -100%; transition-delay: 0.7s;" class="credit-card front" id="frontSide">
        <div class="card-title">CREDIT CARD</div>

        <div class="card-number">
            <div class="card-number-label">CARD NUMBER</div>
            <div class="card-numbers">
                <input type="text" class="tbx-number-0" maxlength='4' name="1"/>
                <input type="text" class="tbx-number-1" maxlength='4' name="2"/>
                <input type="text" class="tbx-number-2" maxlength='4' name="3"/>
                <input type="text" class="tbx-number-3" maxlength='4' name="4"/>
            </div>
        </div>

        <div class="card-expiration">
            <div class="card-expiration-label">
                <div>VALID</div>
                <div>THRU</div>
            </div>
            <div class="card-expiration-month">
                <div class="card-expiration-month-label">MONTH</div>
                <select class='drp-expiration-month'>
                    <option value="01">01</option>
                    <option value="02">03</option>
                    <option value="03">03</option>
                    <option value="04">04</option>
                    <option value="05">05</option>
                    <option value="06">06</option>
                    <option value="07">07</option>
                    <option value="08">08</option>
                    <option value="09">09</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                    <option value="12">12</option>
                </select>
            </div>
            <div class="card-expiration-slash">/</div>
            <div class="card-expiration-year">
                <div class="card-expiration-year-label">YEAR</div>
                <select class='drp-expiration-year'>
                    <option value="15">15</option>
                    <option value="16">16</option>
                    <option value="17">17</option>
                    <option value="18">18</option>
                    <option value="19">19</option>
                    <option value="20">20</option>
                </select>
            </div>
        </div>
    </div>
    <div style="margin-left: -100%" class="credit-card back unfocused" id="backSide">
        <div class="magnetic-strip"></div>
        <div class="credit-card-ccv">
            <div class="credit-card-ccv-label">CCV CODE</div>
            <div class="credit-card-ccv-strip">
                <div class="credit-card-ccv-box"></div>
                <input type="text" class="tbx-ccv" maxlength='4' name="CV2"/>
                <div class="credit-card-ccv-prefix">XXX</div>
            </div>
        </div>
    </div>

</div>
    <input style="margin-left: -100%" style="width: 150px;text-align: center;margin-top 10vh;
    /* position: fixed; */margin-top: 30vh;margin-left: 30vw;height: 2vh;border-radius: 10px;"
           type="submit" value="Add card" id="butt" name="kkk">
</form>



<script>
    function adddd() {
        console.log(1);
        document.getElementById("backSide").style.marginLeft = "-7vw";
        document.getElementById("frontSide").style.marginLeft = "-7vw";
        document.getElementById("butt").style.marginLeft = "32vw";
        document.getElementById("butt").style.marginTop = "31vh";
        document.getElementById("butt").style.position = "relative";
        document.getElementById("butt").style.zIndex = "3";
    }

    </script>

</body>
</html>
