<!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="../src/styles/header.css">
</head>
<body>
<header>
<!--
<?php if(isset($fromSorted)) {

    include_once ("../Model/AllClients.php");
    $model = new AllClients();
    $model->getAllClients();

    echo "<div style='text-align: center; color: white; padding-top: 12px;'>
    Sum = ".$model->sumAllCredits()."</div>";  }
?>
-->
    <a href="../View/index.phtml" ><img class="back-to-home" style="" src="../src/img/house.png"> </a>
</header>
<div class="vertical-line"></div>
</body>
</html>