<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="../src/styles/inputFind.css" type="text/css">
</head>
<body>
<form class="cont" action="../Controller/find_controller.php" method="post">
    <input class="find" type="text" placeholder="Set number" name="find">
    <input clas="btn-find" type="submit" value="F" name="submit" >
</form>
</body>
</html>